"""add_budget_currency

Revision ID: 1819fcf4500a
Revises: f3c38b2847a9
Create Date: 2026-06-17 07:31:24.831420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1819fcf4500a'
down_revision: Union[str, Sequence[str], None] = 'f3c38b2847a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('currency', sa.String(length=10), nullable=False, server_default='USD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'currency')
    # ### end Alembic commands ###
