"""add role to users

Revision ID: b0d775b61a18
Revises: 
Create Date: 2026-06-11 04:48:31.352573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d775b61a18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency_from', sa.String(length=10), nullable=False),
    sa.Column('currency_to', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_from', 'currency_to', 'date', name='uq_market_price_date')
    )
    op.create_index('ix_market_price_lookup', 'market_prices', ['currency_from', 'currency_to', 'date'], unique=False)
    op.drop_table('marketprices')
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('accounts', 'account_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_accounts_journal_id'), 'accounts', ['journal_id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_unique_constraint('uq_account_journal_name', 'accounts', ['journal_id', 'name'])
    op.add_column('journals', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.add_column('journals', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('journals', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('journals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_journals_owner_id'), 'journals', ['owner_id'], unique=False)
    op.drop_constraint(op.f('journals_user_id_fkey'), 'journals', type_='foreignkey')
    op.create_foreign_key(None, 'journals', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('journals', 'file_path')
    op.drop_column('journals', 'user_id')
    op.add_column('transaction_entries', sa.Column('commodity', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_transaction_entries_account_id'), 'transaction_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_entries_transaction_id'), 'transaction_entries', ['transaction_id'], unique=False)
    op.drop_constraint(op.f('transaction_entries_account_id_fkey'), 'transaction_entries', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_entries', 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('transaction_entries', 'currency')
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('transactions', 'payee',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('transactions', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_transaction_journal_date', 'transactions', ['journal_id', 'date'], unique=False)
    op.create_index('ix_transaction_payee', 'transactions', ['payee'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role')
    op.drop_index('ix_transaction_payee', table_name='transactions')
    op.drop_index('ix_transaction_journal_date', table_name='transactions')
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'payee',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('transactions', 'updated_at')
    op.add_column('transaction_entries', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transaction_entries', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_entries_account_id_fkey'), 'transaction_entries', 'accounts', ['account_id'], ['id'])
    op.drop_index(op.f('ix_transaction_entries_transaction_id'), table_name='transaction_entries')
    op.drop_index(op.f('ix_transaction_entries_account_id'), table_name='transaction_entries')
    op.drop_column('transaction_entries', 'commodity')
    op.add_column('journals', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('journals', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'journals', type_='foreignkey')
    op.create_foreign_key(op.f('journals_user_id_fkey'), 'journals', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_journals_owner_id'), table_name='journals')
    op.alter_column('journals', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('journals', 'updated_at')
    op.drop_column('journals', 'description')
    op.drop_column('journals', 'owner_id')
    op.drop_constraint('uq_account_journal_name', 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_journal_id'), table_name='accounts')
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('accounts', 'account_type',
               existing_type=sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttype', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_column('accounts', 'updated_at')
    op.create_table('marketprices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('currency_from', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('currency_to', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=28, scale=10), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('marketprices_pkey'))
    )
    op.drop_index('ix_market_price_lookup', table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
