"""Add currency to budgets

Revision ID: f7966b5df871
Revises: 1819fcf4500a
Create Date: 2026-06-17 09:08:04.807285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7966b5df871'
down_revision: Union[str, Sequence[str], None] = '1819fcf4500a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('currency', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'currency')
    # ### end Alembic commands ###
