# app/domain/models/mixins.py
"""
Reusable SQLAlchemy ORM column mixins.

All domain models that need a primary key and audit timestamps
should inherit from UUIDMixin and TimestampMixin (in addition to Base).

Inheritance order must be: (UUIDMixin, TimestampMixin, Base)
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Uuid
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func


class UUIDMixin:
    """Adds a UUID primary key that is generated by Python (not the DB)."""

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        sort_order=-10,  # render id first in DDL
    )


def _utcnow() -> datetime:
    """Return current UTC datetime (used as column default/onupdate)."""
    return datetime.now(timezone.utc)


class TimestampMixin:
    """Adds created_at and updated_at audit columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        sort_order=100,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=_utcnow,
        nullable=False,
        sort_order=101,
    )
